#!/bin/bash

# load_secrets.sh - load the secrets into env vars

export PUBLIC_SSH_KEY="-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAXPhuGIGbo0I+Cxb+HOL23/ndDu69wpovd2VLSBXzMlQAAAKCR62gEketo
BAAAAAtzc2gtZWQyNTUxOQAAACAXPhuGIGbo0I+Cxb+HOL23/ndDu69wpovd2VLSBXzMlQ
AAAED5DU6LAHOKD2zrwPdmlOeZKil+j2otNl+viZW25yBvtBc+G4YgZujQj4LFv4c4vbf+
d0O7r3Cmi93ZUtIFfMyVAAAAGGJvYidzIGdlbmVyYWwgZWQyNTUxOSBJRAECAwQF
-----END OPENSSH PRIVATE KEY-----"

export TAILSCALE_AUTHKEY="tskey-auth-k5gPGdT3zV11CNTRL-bzT1DNRjKi9jADzYex5th9rECwSRUGtS"
